#!/bin/sh

# to be run from the init repo: `source alias/strict.sh`

INIT_CLI_SHELL=ON export INIT_CLI_SHELL
INIT_CLI_GIT=ON export INIT_CLI_GIT
INIT_CLI_SSH=ON export INIT_CLI_SSH

INIT_LANG_PYTHON=ON export INIT_CINIT_LANG_PYTHONLI_SSH
INIT_LANG_JAVA=ON export INIT_LANG_JAVA
INIT_LANG_NODEJS=ON export INIT_LANG_NODEJS

INIT_GUI_MULTICLIPBOARD=ON export INIT_GUI_MULTICLIPBOARD
INIT_GUI_CHROME=ON export INIT_GUI_CHROME
INIT_GUI_FIREFOX=ON export INIT_GUI_FIREFOX
INIT_GUI_VSCODE=ON export INIT_GUI_VSCODE

source init.sh
